export const FETCH_USER = 'FETCH_USER';
export const FETCH_REPO = 'FETCH_REPO';
export const FETCH_USER_STARGAZERS = 'FETCH_USER_STARGAZERS';
export const FETCH_REPO_STARGAZERS = 'FETCH_REPO_STARGAZERS';

export const LOGGED_IN = 'LOGGED_IN';

export const LOCALE_SWITCHED = 'LOCALE_SWITCHED';
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const FETCH_LANGUAGES = 'FETCH_LANGUAGES';
export const POST_RESERVATION_SUCCESS = 'POST_RESERVATION_SUCCESS';
export const POST_RESERVATION_FAILED = 'POST_RESERVATION_FAILED';
export const POST_RESERVATION_PENDING = 'POST_RESERVATION_PENDING';
export const CLEAR_RESERVATION = 'CLEAR_RESERVATION';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
