// Locales
export const LOCALE_SWITCHED = 'LOCALE_SWITCHED';

// Dev errors
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

// Reservations
export const POST_RESERVATION_SUCCESS = 'POST_RESERVATION_SUCCESS';
export const POST_RESERVATION_FAILED = 'POST_RESERVATION_FAILED';
export const POST_RESERVATION_PENDING = 'POST_RESERVATION_PENDING';
export const REPLY_RESERVATION = 'REPLY_RESERVATION';
export const REPLY_RESERVATION_PENDING = 'REPLY_RESERVATION_PENDING';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const FETCH_RESERVATIONS_PENDING = 'FETCH_RESERVATION_PENDING';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const DELETE_RESERVATION_PENDING = 'DELETE_RESERVATION_PENDING';
export const CLEAR_RESERVATION = 'CLEAR_RESERVATION';

// Login
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOGGED_IN = 'LOGGED_IN';
