import memoize from 'lru-memoize';
import {
  createValidator,
  required,
  requiredKid,
  selectOption,
  selectDateOptionKid,
  selectOptionKid,
  maxLength,
  email,
  phoneNumber } from '../../utils/validation';

export const fields = [

  // PARENT FORM
  'firstname',
  'lastname',
  'address',
  'emailAddress',
  'primaryPhoneNumber',
  'optionalPhoneNumber',
  'profession',
  'language',

  // KIDS
  'kid1firstname',
  'kid1lastname',
  'kid1birthDay',
  'kid1birthMonth',
  'kid1birthYear',
  'kid1language',
  'kid1sex',

  'kid2firstname',
  'kid2lastname',
  'kid2birthDay',
  'kid2birthMonth',
  'kid2birthYear',
  'kid2language',
  'kid2sex',

  'kid3firstname',
  'kid3lastname',
  'kid3birthDay',
  'kid3birthMonth',
  'kid3birthYear',
  'kid3language',
  'kid3sex',

  'kid4firstname',
  'kid4lastname',
  'kid4birthDay',
  'kid4birthMonth',
  'kid4birthYear',
  'kid4language',
  'kid4sex',

  'kid5firstname',
  'kid5lastname',
  'kid5birthDay',
  'kid5birthMonth',
  'kid5birthYear',
  'kid5language',
  'kid5sex',

  'kid6firstname',
  'kid6lastname',
  'kid6birthDay',
  'kid6birthMonth',
  'kid6birthYear',
  'kid6language',
  'kid6sex',

  'kid7firstname',
  'kid7lastname',
  'kid7birthDay',
  'kid7birthMonth',
  'kid7birthYear',
  'kid7language',
  'kid7sex',

  'kid8firstname',
  'kid8lastname',
  'kid8birthDay',
  'kid8birthMonth',
  'kid8birthYear',
  'kid8language',
  'kid8sex',

  'kid9firstname',
  'kid9lastname',
  'kid9birthDay',
  'kid9birthMonth',
  'kid9birthYear',
  'kid9language',
  'kid9sex',

  'kid10firstname',
  'kid10lastname',
  'kid10birthDay',
  'kid10birthMonth',
  'kid10birthYear',
  'kid10language',
  'kid10sex',

];

const reservationFormValidation = createValidator({
  firstname: required,
  lastname: required,
  address: required,
  emailAddress: [required, email],
  profession: [required, maxLength(30)],
  primaryPhoneNumber: [required, phoneNumber],
  optionalPhoneNumber: [phoneNumber],
  language: [selectOption],

  kid1firstname: requiredKid,
  kid2firstname: requiredKid,
  kid3firstname: requiredKid,
  kid4firstname: requiredKid,
  kid5firstname: requiredKid,
  kid6firstname: requiredKid,
  kid7firstname: requiredKid,
  kid8firstname: requiredKid,
  kid9firstname: requiredKid,
  kid10firstname: requiredKid,

  kid1lastname: requiredKid,
  kid2lastname: requiredKid,
  kid3lastname: requiredKid,
  kid4lastname: requiredKid,
  kid5lastname: requiredKid,
  kid6lastname: requiredKid,
  kid7lastname: requiredKid,
  kid8lastname: requiredKid,
  kid9lastname: requiredKid,
  kid10lastname: requiredKid,

  kid1birthDay: selectDateOptionKid,
  kid2birthDay: selectDateOptionKid,
  kid3birthDay: selectDateOptionKid,
  kid4birthDay: selectDateOptionKid,
  kid5birthDay: selectDateOptionKid,
  kid6birthDay: selectDateOptionKid,
  kid7birthDay: selectDateOptionKid,
  kid8birthDay: selectDateOptionKid,
  kid9birthDay: selectDateOptionKid,
  kid10birthDay: selectDateOptionKid,

  kid1birthMonth: selectDateOptionKid,
  kid2birthMonth: selectDateOptionKid,
  kid3birthMonth: selectDateOptionKid,
  kid4birthMonth: selectDateOptionKid,
  kid5birthMonth: selectDateOptionKid,
  kid6birthMonth: selectDateOptionKid,
  kid7birthMonth: selectDateOptionKid,
  kid8birthMonth: selectDateOptionKid,
  kid9birthMonth: selectDateOptionKid,
  kid10birthMonth: selectDateOptionKid,

  kid1birthYear: selectDateOptionKid,
  kid2birthYear: selectDateOptionKid,
  kid3birthYear: selectDateOptionKid,
  kid4birthYear: selectDateOptionKid,
  kid5birthYear: selectDateOptionKid,
  kid6birthYear: selectDateOptionKid,
  kid7birthYear: selectDateOptionKid,
  kid8birthYear: selectDateOptionKid,
  kid9birthYear: selectDateOptionKid,
  kid10birthYear: selectDateOptionKid,

  kid1language: selectOptionKid,
  kid2language: selectOptionKid,
  kid3language: selectOptionKid,
  kid4language: selectOptionKid,
  kid5language: selectOptionKid,
  kid6language: selectOptionKid,
  kid7language: selectOptionKid,
  kid8language: selectOptionKid,
  kid9language: selectOptionKid,
  kid10language: selectOptionKid,

  kid1sex: selectOptionKid,
  kid2sex: selectOptionKid,
  kid3sex: selectOptionKid,
  kid4sex: selectOptionKid,
  kid5sex: selectOptionKid,
  kid6sex: selectOptionKid,
  kid7sex: selectOptionKid,
  kid8sex: selectOptionKid,
  kid9sex: selectOptionKid,
  kid10sex: selectOptionKid,

});

export default memoize(10)(reservationFormValidation);
